---
title: "Cancer Data"
format: html
runtime: shiny
---
```{r}
#| echo: false
library(reactable)
library(dplyr)
library(tidyverse)
library(shiny)
```

```{r}
#| echo: false
Data_Guys_20<-readRDS("./Data_Guys_20.RDS")
table1<-readRDS("./table1.RDS")
table2<-readRDS("./table2.RDS")
```


```{r}
#| echo: false
library(shiny)

tables <- list(
  "Guys and St Thomas_Q2" = table1,
  "South Tyneside and Sunderland NHS Foundation Trust_Q1" = table2
)
```


```{r}
ui <- fluidPage(
  titlePanel("Dropdown List"),
  sidebarLayout(
    sidebarPanel(
      selectInput("hospital", "Choose an option:", 
                  choices = c("South Tyneside and Sunderland NHS Foundation Trust", "Guys and St Thomas", 
                              "Ashford and St Peters Hospitals NHS Foundation Trust")),
      selectInput("quarter_year", "Choose a Quarter:", choices = c("Q1", "Q2")),
                  ),
           mainPanel(
               uiOutput("table")
              )
        ))

server <- function(input, output, session) {
 output$table <- renderUI({
    
    table_key <- paste(input$hospital, input$quarter_year, sep = "_")
    
    # Retrieve the correct dataset
    if (table_key %in% names(tables)) {
      tables[[table_key]]
    } else {
      NULL  # In case of missing data
    }
  })
}


shinyApp(ui, server)
```

